### ISSUE TITLE
pacemaker resources 

### ISSUE THREAD

**Issue by relumer** [devgateway/ansible-role-pacemaker#2]
Hello
This is from your example playbook

pacemaker_resources:
          - id: dns-ip
            type: "ocf:heartbeat:IPaddr2"
            options:
              ip: 10.0.0.1
              cidr_netmask: 8

Do i have to enter a virtual/floating IP in ip:?

thank you

**Comment by styopa** [comment]
Hi,

Yes, this is an option from this resource for the virtual IP address. You can get detailed info by running:
`pcs resource describe ocf:heartbeat:IPaddr2`
