### ISSUE TITLE
ported to Debian

### ISSUE THREAD

**Issue by relumer** [devgateway/ansible-role-pacemaker#7]
Hi
i have finnaly ported your role to Debian 9 . Everything works except the part that you have to create corosync-keygen , i did that manually. I still need to figure out how to do it with ansible. 

For debian8 the role fails miserably . You have to use jessie backports but even then packages don;t install for some reason. 

I can share the edited role with you if you are interested

the other 2 issues still remain open ..

**Comment by styopa** [comment]
Thank you! Sure, I'd love to see the Debian version.
