### ISSUE TITLE
prevent creation of pacemaker_resources multiple times

### ISSUE THREAD

**Issue by marcindulak** [devgateway/ansible-role-pacemaker#9]
It looks to me that there is nothing in the code https://github.com/styopa/ansible-pacemaker/blob/1ed86d75da60828ef1758f0b44c08cc4839f9283/tasks/main.yml#L50 to prevent from trying to create already defined pacemaker_resources on the cluster.

Take the following 2-node scenario:

1. node1 defines pacemaker_resources
2. run ansible again on node1 - pacemaker_resources will get defined again?
3. node1 fails, and node2 becomes the only nodes in the cluster
4. node1 is reinstalled from scratch - pacemaker_resources are defined again unaware of node2 being present?

**Comment by MichaelLeeHobbs** [comment]
#10 Addresses this in a backwards way.

**Comment by styopa** [comment]
Thank you guys for the notice and for the pull request! I updated the role to do it somewhat idempotently.
